In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [52]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a = range(1000)
%timeit [i*2 for i in a]

88.2 µs ± 2.94 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [54]:
b = np.arange(1000)
%timeit b*2

1.88 µs ± 111 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [59]:
nump = np.arange(5)
nump

array([0, 1, 2, 3, 4])

In [58]:
a=[1,2,3,4]
a[1::2]

[2, 4]

In [61]:
nump = np.arange(1,4)
nump

array([1, 2, 3])

In [94]:
a = [[1,3,5],[6,2,8],[6,8,4]]
a

[[1, 3, 5], [6, 2, 8], [6, 8, 4]]

In [100]:
a=np.array([[1,3,5,6,7],[6,2,8,7,5]])
a

array([[1, 3, 5, 6, 7],
       [6, 2, 8, 7, 5]])

In [104]:
a[1][1]

2

In [86]:
a=np.array([[1,3],[6,2]])
b=np.array([[2,3],[5,1]])
a*b

array([[ 2,  9],
       [30,  2]])

In [84]:
a

array([[1, 3],
       [6, 2]])

In [85]:
b

array([[2, 3],
       [5, 1]])

In [81]:
a.sum(axis=0)

array([13, 13, 17])

In [87]:
a.mean()

3.0

In [88]:
np.median(a, axis=1) #axis=0 is column

array([2., 4.])

In [89]:
a.std()

1.8708286933869707

In [90]:
a.T

array([[1, 6],
       [3, 2]])

In [47]:
df = pd.read_csv("train.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

#Data Dictionary

1. Variable	    Definition	        Key
2. survival	    Survival	        0 = No, 1 = Yes
3. pclass	    Ticket class        1 = 1st, 2 = 2nd, 3 = 3rd
4. sex	        Gender	
5. Age	        Age in years	
6. sibsp	    # of siblings / spouses aboard the Titanic	
7. parch	    # of parents / children aboard the Titanic	
8. ticket	    Ticket number	
9. fare	        Passenger fare	
10. cabin	    Cabin number	
11. embarked	Port of Embarkation	 C = Cherbourg, Q = Queenstown, S = Southampton

In [91]:
df.shape

(891, 12)

In [48]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [92]:
df['Age'].median()

28.0